#!/usr/bin/env zsh
# parser generated by file-extension-list
# see: https://github.com/dyne/file-extension-list

function file-extension-parser() {
    ext=${1##*.}
    case ${ext:l} in
        7z|a|apk|ar|bz2|cab|cpio|deb|dmg|egg|gz|iso|jar|lha|mar|pea|rar|rpm|s7z|shar|tar|tbz2|tgz|tlz|war|whl|xpi|zip|zipx|xz|pak)
            print archive ;;
        aac|aiff|ape|au|flac|gsm|it|m3u|m4a|mid|mod|mp3|mpa|pls|ra|s3m|sid|wav|wma|xm)
            print audio ;;
        3dm|3ds|max|bmp|dds|gif|jpg|jpeg|png|psd|xcf|tga|thm|tif|tiff|yuv		%|ai|eps|ps|svg|dwg|dxf|gpx|kml|kmz|webp)
            print image ;;
        doc|docx|ebook|log|md|msg|odt|org|pages|pdf|rtf|rst|tex|txt|wpd|wps)
            print text ;;
        1.ada|2.ada|ada|adb|ads|asm|bas|bash		%|bat		%|c|c++|cbl|cc|class|clj|cob|cpp|cs|csh		%|cxx|d|diff|e|el|f|f77|f90|fish		%|for|fth|ftn|go|groovy|h|hh|hpp|hs|html|hxx|java|js|jsp|ksh		%|kt|lhs|lisp|lua|m|m4|nim|patch|php|pl|po|pp|py|r|rb|rs|s|scala|sh		%|swg|swift|v|vb|vcxproj|xcodeproj|xml|zsh		%)
            print code ;;
        3g2|3gp|aaf|asf|avchd|avi|drc|flv|m2v|m4p|m4v|mkv|mng|mov|mp2|mp4|mpe|mpeg|mpg|mpv|mxf|nsv|ogg|ogv|ogm|qt|rm|rmvb|roq|srt|svi|vob|webm|wmv|yuv)
            print video ;;
        eot|otf|ttf|woff|woff2)
            print font ;;
        exe|msi|bin|command|sh|bat|crx|bash|csh|fish|ksh|zsh)
            print exec ;;
        mobi|epub|azw1|azw3|azw4|azw6|azw|cbr|cbz)
            print book ;;
        html	%|htm		%|css|js		%|jsx		%|less|scss|wasm|php		%)
            print web ;;
        ods|xls|xlsx|csv|ics|vcf)
            print sheet ;;
        ppt|odp)
            print slide ;;
        *) print other ;;
	esac
}

